<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\TwinLabs.Core\TwinLabs.Core.csproj" />
    <ProjectReference Include="..\TwinLabs.Connect\TwinLabs.Connect.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="OPCFoundation.NetStandard.Opc.Ua.Client" Version="1.5.378.182" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="TwinLabs.Connect.OpcUa.Tests" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
